### ISSUE TITLE
PUMS SOC to BLS SOC crosswalk update

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-tracker#20]
Several BLS SOC codes in the new ONET data are missing mappings to similar PUMS codes. Need to update the crosswalk.

**Comment by jspeis** [comment]
Seems this one looks good to go with the crosswalk you shared. Ok to close this one out?

**Comment by hwchen** [comment]
Finished in onet-core. Mapping was completed without manual intervention by matching on higher levels of the classification hierarchy.
