### ISSUE TITLE
re-ingest 2016 language tables (B16001)

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#254]
it's missing data at certain levels: https://flint-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJHZW9ncmFwaHkiLCJDb3VudHkiLCJDb3VudHkiXV0sImN1dHMiOltdLCJjdWJlIjoiYWNzX3lnbF9sYW5ndWFnZV9zcG9rZW5fYXRfaG9tZV9ieV9lbmdsaXNoX2FiaWxpdHlfMjAxNl81IiwibWVhc3VyZXMiOlsiTGFuZ3VhZ2VzIFNwb2tlbiJdfQ==

**Comment by jspeis** [comment]
@davelandry @innerstage I have a feeling this is the same issue that was recently noticed with regard to Cambridge as @innerstage mentioned there was no data in the source.
