### ISSUE TITLE
add "BUCKET" dim_type annotations

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#259]
- [x] "Wage Bin" (`pums_1/5`)
- [x] "Age" dimension (`pums`)
- [x] all "Age" dimensions (`acs`)
- [x] "Household Income Bucket" (`acs_yg_household_income_1/5`)
- [x] "Value Bucket" (`acs_ygo_housing_value_bucket_1/5`)

**Comment by davelandry** [comment]
@jspeis @hwchen I'd like to take on these annotation changes, can either of you point me to the correct repo?

**Comment by jspeis** [comment]
@davelandry checkout the [development branch of the repo](https://github.com/Datawheel/datausa-mondrian). You should be able to directly edit the cubes' inside the `frags` repo. There are a few small steps after that before it gets deployed but if you can make the edits I can handle that.
