### ISSUE TITLE
confirm health numbers with melissa

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-tracker#260]

**Comment by jspeis** [comment]
Spoke with Melissa today and I believe we are now all on the same page. We will use the non-exclusive healthcare numbers. The advantage here is that this will cover more of the different varieties of health care (otherwise, with exclusive coverage we will lose resolution as ~77M double coveragees would get grouped into an "Other" group for privacy). The disadvantage here is that we can not show visualization that present the data as a share of the total health care coverage plans -- though we will be able to show rates as a function of the covered population. We will likely need to collaborate with Melissa and review the Census documentation to make sure we get the precise wording right and provide contextual footnotes to explain the issues relating to double counting of non-exclusive coverages.

**Comment by davelandry** [comment]
great @jspeis 👍 

where are we with the data ETL? can we only now just get started, or is there a separate issue for that already in progress?

**Comment by jspeis** [comment]
So now that what we've confirmed the data scope we can proceed with the ETL part. I'll add a separate issue for that
