### ISSUE TITLE
update BEA data

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-tracker#261]
new 2017 data is available

**Comment by davelandry** [comment]
@jspeis what repo has the actual ETL for this? (coming from the guise of "do we need this datausa-tracker repo now that we have the whiteboard?")

**Comment by jspeis** [comment]
@davelandry it's in https://github.com/Datawheel/bamboo-bea-pipeline/

Now that we have the whiteboard I think we can start to sunset the tracker

**Comment by davelandry** [comment]
@jspeis do you want to move that repo (and any other ones in Datawheel) over to the DataUSA org?

**Comment by jspeis** [comment]
I'd like to keep those inside Datawheel for now.
