### ISSUE TITLE
update PUMS degree field captions

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#263]
@jspeis I'm looking to add captions to a couple of PUMS dimensions (per Cesar's request). How would I go about doing this? Is it as simple as adding an attribute/value like this?

```xml
<Level column="cip2" nameColumn="cip2_name" name="CIP2" caption="2 Digit Course" uniqueMembers="true"/>
```

**Comment by jspeis** [comment]
@davelandry I've never used that before but it appears -- technically -- that could work. The front-end would just need to know to display the `caption` field for that level instead of the "name"

**Comment by davelandry** [comment]
As long as that's what comes through the `/cubes` and "members" endpoints as the "caption", we should be all set on the front-end, thanks! 👍
