### ISSUE TITLE
place names in transport time table have duplicate state suffixes

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#266]
Place names are coming through as `"New York, NY, NY"`: https://halite-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJHZW9ncmFwaHkiLCJQbGFjZSIsIlBsYWNlIl1dLCJjdXRzIjpbXSwiY3ViZSI6ImFjc195Z3RfbWVhbl90cmFuc3BvcnRhdGlvbl90aW1lX3RvX3dvcmtfMSIsIm1lYXN1cmVzIjpbIkF2ZXJhZ2UgQ29tbXV0ZSBUaW1lIl19

**Comment by jspeis** [comment]
@Jayrmajithia It appears these suffixes became duplicated in the `shapes2017`.`places` database tables. I believe you may have recently made some changes to this table Would you be able to de-duplicate the suffixes in the `name` column?

* [ ] backend-v4 `shapes2017.places` (monetdb0
* [x] zcube-v4: `shapes2017.places` (postgres)

**Comment by Jayrmajithia** [comment]
I have fixed the issue of the duplicate state suffix in the shapes2017.places in Postgres which was affected. And also fixed the other tables having issues in their short-name in the PostgresDB. There was no effect of my update in the MonetDB database

**Comment by jspeis** [comment]
great work @Jayrmajithia this appears to be fixed https://iron-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJHZW9ncmFwaHkiLCJQbGFjZSIsIlBsYWNlIl1dLCJjdXRzIjpbXSwiY3ViZSI6ImFjc195Z3RfbWVhbl90cmFuc3BvcnRhdGlvbl90aW1lX3RvX3dvcmtfMSIsIm1lYXN1cmVzIjpbIkF2ZXJhZ2UgQ29tbXV0ZSBUaW1lIl19

**Comment by davelandry** [comment]
confirmed fixed on the front-end! (just need to clear the front-end cache before launch)
