### ISSUE TITLE
ACS 1-year mean transportation time to work aggregation issue

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#268]
All of the 2018 look to be cumulative, making for a _very_ long commute time 😆 

https://iron-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJHZW9ncmFwaHkiLCJOYXRpb24iLCJOYXRpb24iXSxbIlllYXIiLCJZZWFyIiwiWWVhciJdXSwiY3V0cyI6W10sImN1YmUiOiJhY3NfeWd0X21lYW5fdHJhbnNwb3J0YXRpb25fdGltZV90b193b3JrXzEiLCJtZWFzdXJlcyI6WyJBdmVyYWdlIENvbW11dGUgVGltZSJdfQ==

**Comment by jspeis** [comment]
Looks better now!
