### ISSUE TITLE
IPEDS data

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-tracker#269]
* [x] University table  (@jspeis) -- depends on #271 to be completed
* [x] Admissions  (@jspeis)
* [x] Degrees awarded (@jspeis)
* [x] Enrollment  (@jspeis)
* [x] Graduation demographics  (@jspeis)
* [x] Graduation timeframe  (@jspeis)
* [x] Retention rates  (@jspeis)
* [x] Tuition, Overall (@jspeis)
* [x] Living expenses (@jspeis)
* [x] Tuition by CIP (@jspeis)
* [ ] Financials (@innerstage)
* [ ] Expenses (@innerstage)
* [ ] Instructional salaries (@innerstage)
* [ ] Non instructional salaries (@innerstage)
* [ ] Student aid (@innerstage)
* [ ] Student aid by living arrangement (@innerstage)
* [ ] University aid (@innerstage)

**Comment by jspeis** [comment]
@davelandry I've started updating some of the IPEDS datasets to 2017. Is there anything special that needs to happen on the frontend side to have the newer data displayed? (I cleared the nginx/mondrian cache caches) e.g. https://iron.datausa.io/profile/university/harvard-university#admissions ... not all the datasets are 2017 yet but would be very helpful to be able to see as we go

**Comment by davelandry** [comment]
@jspeis you either need to clear the front-end `api/data` cache, or just manually hit a "new" URL to verify: https://iron.datausa.io/api/data?University=166027&measures=Admissions%20Total,Applicants%20Total&year=all

(I took the "view data" URL from that viz, and added `year=all` to the end of it)

**Comment by jspeis** [comment]
As updates:

Just updated the IPEDS university dimension table to reflect the latest IPEDS data updates and add in plumbing for congressional district support in IPEDS (thanks @Jayrmajithia for updating the shapefiles!).

And currently reviewing @innerstage's work on the aid data

**Comment by jspeis** [comment]
Great work by @innerstage on getting the aid data ready. Only 4 datasets left, though these datasets appear to have some breaking changes

**Comment by jspeis** [comment]
all in! now just have to run some data quality checks

**Comment by jspeis** [comment]
previous backend server appears to have gotten into a corrupted state (when the server is replicated, it doesnt boot properly) so out of an abundance of caution we are going to re-ingest the data

**Comment by jspeis** [comment]
(BTW only need to reingest to the Monet server not postgres)
