### ISSUE TITLE
update O*NET data

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#272]

**Comment by jspeis** [comment]
great work by @Jayrmajithia porting this to bamboo. It seems like the scope of ONET's updates  was _very_ narrow but some SOCs/CIPs have new data now
<img width="1500" alt="Screen Shot 2019-11-20 at 4 27 53 PM" src="https://user-images.githubusercontent.com/87581/69279682-e6a6d980-0bb2-11ea-876b-3d33b0d3eaab.png">
