### ISSUE TITLE
PUMS dimension updates

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-tracker#276]
Before PUMS data can be updated, we will need to update PUMS dimension tables because of breaking changes:

* [x] Place of Birth
* [x] PUMS NAICS
* [x] PUMS SOC

**Comment by jspeis** [comment]
I'm updating the 2018 PUMS dimensions now. Just as a heads up @davelandry there are ~20 new industry IDs and ~140 new occupation codes. Some of these are purely new and some are splits/combinations of existing codes.

**Comment by jspeis** [comment]
So as of the 2018 PUMS data, there is no more "Hospitals" NAICS code (622), it has been split to:

            622M               General Medical And Surgical Hospitals, And Specialty (Except Psychiatric And Substance Abuse) Hospitals
            6222               Psychiatric And Substance Abuse Hospitals

FYI @davelandry since "Hospitals" is one of the industries from the homepage, might want to rotate that?

**Comment by jspeis** [comment]
Attaching new 2018 PUMS NAICS/SOCs for reference
[new-naics-soc.zip](https://github.com/DataUSA/datausa-tracker/files/3893927/new-naics-soc.zip)

**Comment by davelandry** [comment]
👍 working in front-end
