### ISSUE TITLE
ACS internet table is missing some groups

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#282]
Old table: https://iron-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJJbnRlcm5ldCBBY2Nlc3MiLCJJbnRlcm5ldCBBY2Nlc3MiLCJBY2Nlc3MgVHlwZSJdXSwiY3V0cyI6W10sImN1YmUiOiJhY3NfeWdoX2hvdXNlaG9sZHNfd2l0aF9ub19pbnRlcm5ldF8xIiwibWVhc3VyZXMiOlsiSG91c2Vob2xkcyBieSBJbnRlcm5ldCBBY2Nlc3MiXX0=

New table: https://iron-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJJbnRlcm5ldCBBY2Nlc3MiLCJJbnRlcm5ldCBBY2Nlc3MiLCJBY2Nlc3MgVHlwZSJdXSwiY3V0cyI6W10sImN1YmUiOiJhY3NfeWdoX2hvdXNlaG9sZHNfd2l0aF9ub19pbnRlcm5ldF8yMDE2XzEiLCJtZWFzdXJlcyI6WyJIb3VzZWhvbGRzIGJ5IEludGVybmV0IEFjY2VzcyJdfQ==

**Comment by Jayrmajithia** [comment]
@davelandry There have been table changes in the B28002 from the year 2016 the number columns have been reduced to 7 in the old version we were not updating the table after 2015. There was no update after 2015 because the config file contained the fewer columns which raised an error while performing ETL for the B28002 for the year 2016, 2017, 2018

**Comment by davelandry** [comment]
Ahh ok, well this complicates things because we were using the "no internet coverage" group to calculate an overall percentage of people with no internet coverage.

@jspeis @Jayrmajithia for now I am just favoring the old cube in the node logic layer, but how would you see us calculating this for the new data?

**Comment by jspeis** [comment]
@davelandry @Jayrmajithia seems like the data is available but from a new table? e.g.

https://censusreporter.org/data/table/?table=B28011&geo_ids=16000US3651000&primary_geo_id=16000US3651000

maybe we switch to that source if it otherwise has the information we need?

**Comment by jspeis** [comment]
although @Jayrmajithia seems like B28002 also has additional items: https://censusreporter.org/data/table/?table=B28002&geo_ids=04000US36&primary_geo_id=04000US36

**Comment by Jayrmajithia** [comment]
@davelandry  Updated the table with the Access group changes. It should not be an issue.
