### ISSUE TITLE
Dartmouth Data

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-tracker#29]
* [x] Ingest Dartmouth Atlas of Health Data
* [x] Create Schema

**Comment by davelandry** [comment]
@jspeis are you ingesting this from the previous db, or straight from the source (this was a Deloitte/Kevin Denny dataset)

**Comment by jspeis** [comment]
We are going to use existing database as a source for these since the raw files shared had errors in them (and I don't think they were ever corrected)

**Comment by jspeis** [comment]
Ingested the reimbursement table and the 3 measures Melissa request. Will re-open if more are needed

**Comment by jspeis** [comment]
* [ ] Hospital Reimbursements
