### ISSUE TITLE
senator name cleanup

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#296]
States with an "Other" senator:
- [x] Colorado
- [x] Delaware
- [x] Georgia
- [x] Illinois
- [x] Virginia

Manual name changes:
- [x] Mississippi: Roger Sen. Wicker (Roger Wicker)
- [x] North Carolina: Thom R. Sen. Tillis (Thom Tillis)
- [x] North Carolina: Hel Jesse (Jesse Helms)
- [x] Ohio: Rob The Honora Portman (Rob Portman)
- [x] Oklahoma: James M. Sen Inhofe (Jim Inhofe)
- [x] Texas: John Sen Cornyn (John Cornyn)
- [x] Texas: Rafael Edward Ted Cruz (Ted Cruz)
- [x] Utah: Willard Mitt Mr Romney (Mitt Romney)
- [x] Vermont: Bernard Sanders (Bernie Sanders)
- [x] Virginia: Timothy Michael Kaine (Tim Kaine)

**Comment by jspeis** [comment]
@innerstage while doing this just make sure that each `candidate_id` has one *and only one* candidate spelling (otherwise, this can cause problems for Mondrian if one `candidate_id` has two different `caniddate`s .. so we should add a check for this in the pipeline)
