### ISSUE TITLE
stand up malachite

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#298]
- [x] create `zcube-v7` from `zcube-v6`
- [x] create `malachite` from `keyite`
- [x] update NGINX config to point to `zcube-v7` and `backend-v7`
- [x] create `api-ts.datawheel.us` DNS record pointing to `tesseract-v7`

questions for Jonathan:
- [x] why is _some_ data duplicated across zcube and backend?
- [x] why are we using the load balancer instance groups for production?

Supporting docs:
- https://docs.google.com/presentation/d/1TaxwYwaizuCcL-u3AXt1hAIY_1ZO_YgQGJ5zx-68nP4/edit#slide=id.g8a2e0d68cd_0_23
- https://github.com/Datawheel/company/wiki/Data-USA-Server-Configuration-Documentation

**Comment by mcastillomolina** [comment]
The goal is to move from mondrian api to tesseract ? Tasks 1, 2 and 4 are done. Going for 3 and 5 now

**Comment by davelandry** [comment]
Yes, we want to move everything to tesseract... _eventually_. There's A LOT of data here, so I want to be strategic about a slow migration to tesseract (because the front-end systems, like the vizbuilder, can theoretically use both mondrian and tesseract at the same time!). For this current `malachite` task, I just want to test if that's even possible. @innerstage only has 2 cubes on that tesseract server (BLS unemployment), so I just want to fold those into our current backend stack (going from 2 databases to 3).
