### ISSUE TITLE
add basic NGINX proxy cache to api-ts routes

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#322]
Steps: https://github.com/Datawheel/bls-employment-etl

UI: https://api-ts.datausa.io/ui/?cube=BLS+Employment+-+Supersector+Only&drilldowns%5B0%5D=Time.Month+of+Year&measures%5B0%5D=NSA+Employees

**Comment by mcastillomolina** [comment]
Data was updated to May 2021, as it can be seen in the raw response, however is not appearing in tesseract UI, I think we are not caching here (?). Maybe it is just a thing of time for the data to appear correctly in the UI (?)

https://api-ts.datausa.io/tesseract/data.jsonrecords?cube=BLS+Employment+-+Supersector+Only&debug=false&drilldowns=Month+of+Year&measures=NSA+Employees&parents=false&sparse=false
