### ISSUE TITLE
remove Universities with no names from ipeds_completions table on topaz

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-tracker#334]

**Comment by mcperez2** [comment]
I enhanced the solution including all tables into the schema `ipeds` in `backend` and `zcube` databases. As outcome we can find the schema `ipeds_backup` which is a backup of  **all old tables** and the schema `ipeds` whose tables just contain universities that are into the `ipeds_dims.university` table. 

The following tables are a summary in each schema, `zcube` and `backend` respectively, where `qt_new`(`qt_old`) is the number of row to the table in `ipeds`(`ipeds_backup`) schema, `diff` is the is the difference between previous columns and `univ_name_null` is just a classified which identify if the old table had null names (where in all cases is `yes`)


|tbl|qt_new|qt_old|diff|univ_name_null|
|---|------|------|----|--------------|
|admissions|12562|12641|79|yes|
|completions|33826140|34352604|526464|yes|
|enrollment|2111544|2208870|97326|yes|
|finance_expenses|319236|324466|5230|yes|
|finance_financials|51025|53638|2613|yes|
|graduation_demographics|274352|289312|14960|yes|
|graduation_demographics_v2|319488|341024|21536|yes|
|graduation_demographics_v3|472304|494992|22688|yes|
|graduation_timeframe|128049|135762|7713|yes|
|ic_living_expenses|89775|92538|2763|yes|
|retention_rates|49999|53100|3101|yes|
|salaries_instructional|169674|171694|2020|yes|
|salaries_noninstructional|400374|411138|10764|yes|
|sfa_aid|219955|230755|10800|yes|
|sfa_living|175964|184604|8640|yes|
|sfa_university|43991|46151|2160|yes|
|tuition|29925|30846|921|yes|
|tuition_by_cip|814749|825953|11204|yes|
|undergrad_grad_rate_demographics|168080|176160|8080|yes|
